CREATE TABLE coloratura_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

ALTER TABLE coloratura_playlists
    ADD COLUMN
        creator INTEGER REFERENCES coloratura_users(id)
        ON DELETE SET NULL;