CREATE TABLE coloratura_tracks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    link TEXT NOT NULL,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    playlist_id INTEGER REFERENCES coloratura_playlists(id) ON DELETE CASCADE NOT NULL
);